In [2]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:", arr1)

arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("\n2D Array:\n", arr2)

print("\nZeros Array:")
print(np.zeros((2, 3)))

print("\nOnes Array:")
print(np.ones((3, 3)))

print("\nIdentity Matrix:")
print(np.eye(4))

print("\nArray with Range:")
print(np.arange(1, 11))

print("\nEven Numbers:")
print(np.arange(2, 21, 2))

print("\nLinearly Spaced Values:")
print(np.linspace(0, 10, 5))

print("\nShape:", arr2.shape)
print("Size:", arr2.size)
print("Dimensions:", arr2.ndim)
print("Data Type:", arr2.dtype)

print("\nAddition:", arr1 + 5)
print("Subtraction:", arr1 - 5)
print("Multiplication:", arr1 * 2)
print("Division:", arr1 / 2)
print("Square:", arr1 ** 2)
print("Square Root:", np.sqrt(arr1))

print("\nSum:", np.sum(arr1))
print("Mean:", np.mean(arr1))
print("Median:", np.median(arr1))
print("Maximum:", np.max(arr1))
print("Minimum:", np.min(arr1))
print("Standard Deviation:", np.std(arr1))
print("Variance:", np.var(arr1))

1D Array: [10 20 30 40 50]

2D Array:
 [[1 2 3]
 [4 5 6]]

Zeros Array:
[[0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Array with Range:
[ 1  2  3  4  5  6  7  8  9 10]

Even Numbers:
[ 2  4  6  8 10 12 14 16 18 20]

Linearly Spaced Values:
[ 0.   2.5  5.   7.5 10. ]

Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int64

Addition: [15 25 35 45 55]
Subtraction: [ 5 15 25 35 45]
Multiplication: [ 20  40  60  80 100]
Division: [ 5. 10. 15. 20. 25.]
Square: [ 100  400  900 1600 2500]
Square Root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]

Sum: 150
Mean: 30.0
Median: 30.0
Maximum: 50
Minimum: 10
Standard Deviation: 14.142135623730951
Variance: 200.0


In [3]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

print("\nFirst Element:", arr1[0])
print("Last Element:", arr1[-1])
print("Elements from Index 1 to 3:", arr1[1:4])

a = np.arange(1, 13)

print("\nOriginal Array:")
print(a)

print("\nReshaped to 3x4:")
print(a.reshape(3, 4))

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\nConcatenated Array:")
print(np.concatenate((a, b)))

arr = np.array([8, 3, 9, 1, 5])

print("\nOriginal:", arr)
print("Sorted:", np.sort(arr))

print("\nRandom Integers:")
print(np.random.randint(1, 100, 5))

print("\nRandom Decimal Numbers:")
print(np.random.rand(3))

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("\nMatrix Addition:")
print(A + B)

print("\nMatrix Subtraction:")
print(A - B)

print("\nMatrix Multiplication:")
print(np.dot(A, B))

print("\nTranspose of Matrix A:")
print(A.T)

print("\nElements Greater Than 25:")
print(arr1 > 25)

print("\nElements Greater Than 25:")
print(arr1[arr1 > 25])

matrix = np.array([[2, 4, 6],
                   [8, 10, 12]])

print("\nRow-wise Sum:")
print(np.sum(matrix, axis=1))

print("\nColumn-wise Sum:")
print(np.sum(matrix, axis=0))


First Element: 10
Last Element: 50
Elements from Index 1 to 3: [20 30 40]

Original Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped to 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Concatenated Array:
[1 2 3 4 5 6]

Original: [8 3 9 1 5]
Sorted: [1 3 5 8 9]

Random Integers:
[95 85 92  8 15]

Random Decimal Numbers:
[0.9967747  0.80277445 0.5240344 ]

Matrix Addition:
[[ 6  8]
 [10 12]]

Matrix Subtraction:
[[-4 -4]
 [-4 -4]]

Matrix Multiplication:
[[19 22]
 [43 50]]

Transpose of Matrix A:
[[1 3]
 [2 4]]

Elements Greater Than 25:
[False False  True  True  True]

Elements Greater Than 25:
[30 40 50]

Row-wise Sum:
[12 30]

Column-wise Sum:
[10 14 18]


In [5]:
import pandas as pd

data = {
    "PassengerId": [1, 2, 3, 4, 5],
    "Survived": [0, 1, 1, 1, 0],
    "Pclass": [3, 1, 3, 1, 2],
    "Name": ["John", "Mary", "David", "Sophia", "James"],
    "Sex": ["male", "female", "male", "female", "male"],
    "Age": [22, 38, 26, 35, 28],
    "SibSp": [1, 1, 0, 1, 0],
    "Parch": [0, 0, 0, 0, 0],
    "Fare": [7.25, 71.28, 7.92, 53.10, 13.00],
    "Embarked": ["S", "C", "S", "S", "Q"]
}

df = pd.DataFrame(data)

In [6]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset("titanic")

print("First 5 Rows:")
print(df.head())

print("\nLast 5 Rows:")
print(df.tail())

print("\nRandom 5 Rows:")
print(df.sample(5))

print("\nShape of Dataset:")
print(df.shape)

print("\nNumber of Rows:")
print(df.shape[0])

print("\nNumber of Columns:")
print(df.shape[1])

print("\nColumn Names:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nDataset Information:")
df.info()

print("\nStatistical Summary:")
print(df.describe())

print("\nSummary Including Categorical Columns:")
print(df.describe(include='all'))

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nUnique Values in Each Column:")
print(df.nunique())

print("\nUnique Passenger Classes:")
print(df["class"].unique())

First 5 Rows:
   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  

Last 5 Rows:
     survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0  